"""
Synthetic Campus Activity Data Generator
========================================
Academic Project: BDS-36 (T.Y. B.Sc. Data Science, Semester V)
Academic Year: 2026-27

SIMULATION DISCLAIMER:
----------------------
All campus activity data generated by this module (electricity_kwh, travel_km,
waste_kg, procurement_inr, student_count, staff_count) is ENTIRELY SYNTHETIC and
SIMULATED for educational, statistical forecasting, and scenario analytics purposes.
It does NOT represent actual utility meter recordings or real financial transactions
from any specific academic institution.

In accordance with PROJECT_SPEC.md:
- Synthetic activity data is explicitly distinguished from external empirical constants.
- No external emission factors are invented in this module.
- All seasonal patterns, building profiles, and variations are parameterized assumptions.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

import numpy as np
import pandas as pd

# Core required columns for campus activity dataset
REQUIRED_COLUMNS: list[str] = [
    "date",
    "building",
    "electricity_kwh",
    "travel_km",
    "waste_kg",
    "procurement_inr",
    "student_count",
    "staff_count",
]


@dataclass(frozen=True)
class BuildingProfile:
    """Archetype profile defining baseline activity levels and sensitivities for a campus building."""

    name: str
    building_type: str
    base_electricity_kwh: float
    base_students: int
    base_staff: int
    travel_km_per_student: float
    travel_km_per_staff: float
    waste_kg_per_student: float
    waste_kg_per_staff: float
    base_procurement_inr: float
    cooling_sensitivity: float = 0.40
    academic_sensitivity: float = 0.50
    procurement_academic_spike: float = 1.45
    procurement_fiscal_spike: float = 1.60


# Default realistic campus buildings covering diverse functional archetypes
DEFAULT_BUILDING_PROFILES: list[BuildingProfile] = [
    BuildingProfile(
        name="Science & Engineering Complex",
        building_type="Laboratories & Research",
        base_electricity_kwh=42000.0,
        base_students=1200,
        base_staff=80,
        travel_km_per_student=24.0,
        travel_km_per_staff=110.0,
        waste_kg_per_student=2.2,
        waste_kg_per_staff=4.5,
        base_procurement_inr=750000.0,
        cooling_sensitivity=0.45,
        academic_sensitivity=0.35,  # Research labs continue during vacations
        procurement_academic_spike=1.55,
        procurement_fiscal_spike=1.70,
    ),
    BuildingProfile(
        name="Academic Block - Arts & Humanities",
        building_type="Classrooms & Lecture Halls",
        base_electricity_kwh=18500.0,
        base_students=1400,
        base_staff=55,
        travel_km_per_student=26.0,
        travel_km_per_staff=105.0,
        waste_kg_per_student=1.8,
        waste_kg_per_staff=3.5,
        base_procurement_inr=180000.0,
        cooling_sensitivity=0.40,
        academic_sensitivity=0.75,  # High vacation drop
        procurement_academic_spike=1.40,
        procurement_fiscal_spike=1.50,
    ),
    BuildingProfile(
        name="Central Library & Student Hub",
        building_type="Study, Workstations & Services",
        base_electricity_kwh=26000.0,
        base_students=1500,
        base_staff=35,
        travel_km_per_student=22.0,
        travel_km_per_staff=95.0,
        waste_kg_per_student=1.9,
        waste_kg_per_staff=3.0,
        base_procurement_inr=320000.0,
        cooling_sensitivity=0.35,
        academic_sensitivity=0.55,
        procurement_academic_spike=1.60,
        procurement_fiscal_spike=1.40,
    ),
    BuildingProfile(
        name="Administrative Headquarters",
        building_type="Offices & Campus Administration",
        base_electricity_kwh=14500.0,
        base_students=250,
        base_staff=95,
        travel_km_per_student=15.0,
        travel_km_per_staff=115.0,
        waste_kg_per_student=1.5,
        waste_kg_per_staff=4.0,
        base_procurement_inr=450000.0,
        cooling_sensitivity=0.35,
        academic_sensitivity=0.15,  # Year-round office operations
        procurement_academic_spike=1.20,
        procurement_fiscal_spike=1.85,  # Major fiscal year-end procurement
    ),
    BuildingProfile(
        name="Hostel & Dining Complex",
        building_type="Residential & Cafeteria",
        base_electricity_kwh=34000.0,
        base_students=850,
        base_staff=30,
        travel_km_per_student=12.0,  # Lower daily commuter travel, students reside on campus
        travel_km_per_staff=85.0,
        waste_kg_per_student=6.5,  # Substantially higher food and dining waste
        waste_kg_per_staff=5.0,
        base_procurement_inr=520000.0,
        cooling_sensitivity=0.30,
        academic_sensitivity=0.80,  # Major drop during summer/winter vacations
        procurement_academic_spike=1.35,
        procurement_fiscal_spike=1.30,
    ),
]

# Monthly seasonal indices (1 = January, ..., 12 = December)
# Reflecting Indian higher education academic calendar:
# - Spring semester: Jan - Apr
# - Summer vacation: May - Jun
# - Monsoon / Autumn semester: Jul - Nov
# - Winter break: Dec
ACADEMIC_CALENDAR_FACTORS: dict[int, float] = {
    1: 0.92,   # Spring semester begins
    2: 1.00,   # Peak spring semester
    3: 1.00,   # Mid-terms and academic activities
    4: 0.95,   # Spring semester concluding exams
    5: 0.45,   # Exams end, summer vacation begins
    6: 0.15,   # Summer vacation - minimum student presence
    7: 0.75,   # Orientation, new admissions, semester kickoff
    8: 1.00,   # Autumn / Monsoon semester full swing
    9: 1.00,   # Peak semester activities
    10: 1.00,  # Cultural/technical festivals & peak attendance
    11: 0.95,  # Semester end preparation and exams
    12: 0.35,  # Winter break and holidays
}

# Climate cooling index (1 to 12)
# Cooling load (AC, refrigeration, ventilation) peaks during hot pre-monsoon & summer:
CLIMATE_COOLING_FACTORS: dict[int, float] = {
    1: 0.80,   # Mild winter - minimal cooling
    2: 0.88,   # Late winter
    3: 1.10,   # Spring warming
    4: 1.30,   # Summer heat
    5: 1.45,   # Peak summer temperatures
    6: 1.38,   # High heat / pre-monsoon
    7: 1.25,   # Monsoon humidity - air conditioning active
    8: 1.20,   # Monsoon cooling load
    9: 1.15,   # Post-monsoon
    10: 1.05,  # Mild autumn
    11: 0.90,  # Transition to winter
    12: 0.80,  # Winter low cooling
}


def _get_building_profiles(
    num_buildings: int,
    building_names: Sequence[str] | None = None,
) -> list[BuildingProfile]:
    """Resolve building profiles based on requested count or custom names."""
    if num_buildings <= 0:
        raise ValueError(f"num_buildings must be a positive integer, got {num_buildings}")

    if building_names is not None:
        if len(building_names) != num_buildings:
            raise ValueError(
                f"Length of building_names ({len(building_names)}) "
                f"must match num_buildings ({num_buildings})"
            )
        profiles = []
        for i, name in enumerate(building_names):
            template = DEFAULT_BUILDING_PROFILES[i % len(DEFAULT_BUILDING_PROFILES)]
            profiles.append(
                BuildingProfile(
                    name=name,
                    building_type=template.building_type,
                    base_electricity_kwh=template.base_electricity_kwh,
                    base_students=template.base_students,
                    base_staff=template.base_staff,
                    travel_km_per_student=template.travel_km_per_student,
                    travel_km_per_staff=template.travel_km_per_staff,
                    waste_kg_per_student=template.waste_kg_per_student,
                    waste_kg_per_staff=template.waste_kg_per_staff,
                    base_procurement_inr=template.base_procurement_inr,
                    cooling_sensitivity=template.cooling_sensitivity,
                    academic_sensitivity=template.academic_sensitivity,
                    procurement_academic_spike=template.procurement_academic_spike,
                    procurement_fiscal_spike=template.procurement_fiscal_spike,
                )
            )
        return profiles

    if num_buildings <= len(DEFAULT_BUILDING_PROFILES):
        return DEFAULT_BUILDING_PROFILES[:num_buildings]

    # Generate additional building profiles systematically if more than default 5 are requested
    profiles = list(DEFAULT_BUILDING_PROFILES)
    for i in range(len(DEFAULT_BUILDING_PROFILES), num_buildings):
        base_idx = i % len(DEFAULT_BUILDING_PROFILES)
        template = DEFAULT_BUILDING_PROFILES[base_idx]
        block_letter = chr(ord("A") + (i // len(DEFAULT_BUILDING_PROFILES)))
        scale = 0.85 + (i % 3) * 0.15
        profiles.append(
            BuildingProfile(
                name=f"{template.name} - Annex {block_letter}",
                building_type=template.building_type,
                base_electricity_kwh=round(template.base_electricity_kwh * scale, 2),
                base_students=int(round(template.base_students * scale)),
                base_staff=int(round(template.base_staff * scale)),
                travel_km_per_student=template.travel_km_per_student,
                travel_km_per_staff=template.travel_km_per_staff,
                waste_kg_per_student=template.waste_kg_per_student,
                waste_kg_per_staff=template.waste_kg_per_staff,
                base_procurement_inr=round(template.base_procurement_inr * scale, 2),
                cooling_sensitivity=template.cooling_sensitivity,
                academic_sensitivity=template.academic_sensitivity,
                procurement_academic_spike=template.procurement_academic_spike,
                procurement_fiscal_spike=template.procurement_fiscal_spike,
            )
        )
    return profiles


def validate_campus_activity_data(df: pd.DataFrame) -> bool:
    """
    Validate the schema, physical bounds, and logical integrity of the campus activity dataset.

    Parameters
    ----------
    df : pd.DataFrame
        The generated or loaded campus activity DataFrame.

    Returns
    -------
    bool
        True if validation passes.

    Raises
    ------
    ValueError
        If any validation rule is violated (missing columns, nulls, negative values,
        invalid dates, or corrupted data).
    """
    if not isinstance(df, pd.DataFrame):
        raise ValueError(f"Expected a pandas DataFrame, got {type(df).__name__}")

    if df.empty:
        raise ValueError("Campus activity DataFrame is empty.")

    # 1. Required columns presence
    missing_cols = [col for col in REQUIRED_COLUMNS if col not in df.columns]
    if missing_cols:
        raise ValueError(f"Missing required column(s): {missing_cols}")

    # 2. No null or NaN values
    null_counts = df[REQUIRED_COLUMNS].isna().sum()
    if null_counts.any():
        cols_with_nulls = null_counts[null_counts > 0].to_dict()
        raise ValueError(f"Dataset contains null values in columns: {cols_with_nulls}")

    # 3. Date validity & sorting
    try:
        parsed_dates = pd.to_datetime(df["date"], format="%Y-%m-%d", errors="raise")
    except Exception as exc:
        raise ValueError(f"Date column contains invalid ISO YYYY-MM-DD date entries: {exc}") from exc

    # Check for duplicates per (date, building)
    duplicates = df.duplicated(subset=["date", "building"])
    if duplicates.any():
        dup_sample = df[duplicates][["date", "building"]].head().to_dict(orient="records")
        raise ValueError(f"Duplicate (date, building) records found: {dup_sample}")

    # Check date monotonicity per building
    for b_name, group in df.groupby("building"):
        group_dates = pd.to_datetime(group["date"])
        if not group_dates.is_monotonic_increasing:
            raise ValueError(f"Dates for building '{b_name}' are not monotonically increasing.")

    # 4. Physical non-negativity constraints
    numeric_cols = [
        "electricity_kwh",
        "travel_km",
        "waste_kg",
        "procurement_inr",
        "student_count",
        "staff_count",
    ]
    for col in numeric_cols:
        negatives = df[df[col] < 0]
        if not negatives.empty:
            raise ValueError(
                f"Negative values detected in column '{col}': {negatives[col].head().tolist()}"
            )

    # 5. Counts must be non-negative integers
    for count_col in ["student_count", "staff_count"]:
        if not pd.api.types.is_integer_dtype(df[count_col]):
            # Check if all floats are exact integers
            if not (df[count_col] % 1 == 0).all():
                raise ValueError(f"Column '{count_col}' must contain integer values.")

    # 6. Non-zero variance check (ensures dataset is dynamic and non-trivial)
    for col in numeric_cols:
        if df[col].std() == 0:
            raise ValueError(f"Column '{col}' has zero variance; expected realistic seasonal variation.")

    return True


def generate_campus_activity_data(
    start_date: str | pd.Timestamp = "2023-01-01",
    end_date: str | pd.Timestamp = "2025-12-01",
    num_buildings: int = 5,
    building_names: Sequence[str] | None = None,
    seed: int = 42,
    validate: bool = True,
    include_simulated_flag: bool = False,
) -> pd.DataFrame:
    """
    Generate realistic monthly synthetic campus activity data covering approximately three years.

    The generator models realistic institutional mechanisms:
    - Academic calendar seasonality (spring semester, summer break, monsoon term, winter break)
    - Climate cooling loads peaking during hot summer / pre-monsoon months
    - Student and staff commuter travel linked to active campus attendance
    - Waste generation reflecting building purpose (dining vs. academic vs. admin)
    - Procurement expenditure dynamics (fiscal year closeout in March, academic start in July/August)
    - Year-over-year baseline growth and stochastic weather/occupancy variations

    Parameters
    ----------
    start_date : str | pd.Timestamp, default '2023-01-01'
        Start date of the monthly series (inclusive, month-start).
    end_date : str | pd.Timestamp, default '2025-12-01'
        End date of the monthly series (inclusive, month-start).
    num_buildings : int, default 5
        Number of campus buildings to simulate.
    building_names : Sequence[str] | None, default None
        Optional explicit building names. If provided, length must equal num_buildings.
    seed : int, default 42
        Reproducible random seed for deterministic generation.
    validate : bool, default True
        Whether to run schema and physical validation on the generated DataFrame.
    include_simulated_flag : bool, default False
        If True, appends an explicit 'is_simulated' column (all True) to the DataFrame.

    Returns
    -------
    pd.DataFrame
        DataFrame with monthly activity data for each building.
    """
    # 1. Parse date range
    start_ts = pd.to_datetime(start_date)
    end_ts = pd.to_datetime(end_date)
    if start_ts > end_ts:
        raise ValueError(f"start_date ({start_date}) cannot be after end_date ({end_date})")

    monthly_dates = pd.date_range(start=start_ts, end=end_ts, freq="MS")
    if len(monthly_dates) == 0:
        raise ValueError("Date range produced zero monthly periods.")

    # 2. Setup building profiles & reproducible RNG
    profiles = _get_building_profiles(num_buildings, building_names)
    rng = np.random.default_rng(seed)

    rows: list[dict] = []
    base_year = monthly_dates[0].year

    for dt in monthly_dates:
        month = dt.month
        year_offset = (dt.year - base_year) + (dt.month - 1) / 12.0
        date_str = dt.strftime("%Y-%m-%d")

        # Seasonal indices
        acad_factor = ACADEMIC_CALENDAR_FACTORS[month]
        clim_factor = CLIMATE_COOLING_FACTORS[month]

        for prof in profiles:
            # 1. Student and Staff Count modeling
            # Student presence varies strongly with academic calendar + small noise
            stud_noise = rng.normal(1.0, 0.02)
            # Active student ratio combines building academic sensitivity with calendar
            effective_stud_ratio = (
                (1.0 - prof.academic_sensitivity) + prof.academic_sensitivity * acad_factor
            )
            student_count = int(
                max(0, round(prof.base_students * effective_stud_ratio * stud_noise))
            )

            # Staff presence is more resilient; modest drop in summer vacation
            staff_noise = rng.normal(1.0, 0.015)
            effective_staff_ratio = 0.88 + 0.12 * acad_factor
            staff_count = int(
                max(1, round(prof.base_staff * effective_staff_ratio * staff_noise))
            )

            # 2. Electricity (kWh)
            # Baseline + cooling load (clim_factor) + occupancy/academic load (acad_factor)
            # Secular annual growth of ~2.5% per year (campus expansion, digitization)
            elec_growth = 1.0 + 0.025 * year_offset
            cooling_component = prof.cooling_sensitivity * (clim_factor - 1.0)
            academic_component = prof.academic_sensitivity * (acad_factor - 1.0)
            elec_noise = rng.normal(1.0, 0.035)

            electricity_kwh = (
                prof.base_electricity_kwh
                * (1.0 + cooling_component + academic_component)
                * elec_growth
                * elec_noise
            )
            electricity_kwh = max(100.0, round(float(electricity_kwh), 2))

            # 3. Travel (km)
            # Commuter travel is driven by active students and staff
            # Working days per month: ~20-22 days in active months, ~6-10 days in vacation
            days_active = 21.0 if acad_factor > 0.8 else (15.0 if acad_factor > 0.4 else 8.0)
            active_travel_ratio = days_active / 21.0

            travel_noise = rng.normal(1.0, 0.04)
            travel_km = (
                (student_count * prof.travel_km_per_student + staff_count * prof.travel_km_per_staff)
                * active_travel_ratio
                * (1.0 + 0.02 * year_offset)
                * travel_noise
            )
            travel_km = max(50.0, round(float(travel_km), 2))

            # 4. Solid Waste (kg)
            # Driven by occupant population and campus activities
            waste_noise = rng.normal(1.0, 0.045)
            # Festival / event bump in February (spring fest) and October (autumn fest)
            event_multiplier = 1.15 if month in (2, 10) else 1.00
            waste_kg = (
                (student_count * prof.waste_kg_per_student + staff_count * prof.waste_kg_per_staff)
                * event_multiplier
                * waste_noise
            )
            waste_kg = max(20.0, round(float(waste_kg), 2))

            # 5. Procurement (INR)
            # Institutional procurement spikes:
            # - March: Fiscal year closeout spending (INR budget exhaustion)
            # - July/August: New academic year setup (lab supplies, textbooks, subscriptions)
            proc_factor = 1.00
            if month == 3:
                proc_factor = prof.procurement_fiscal_spike
            elif month == 7:
                proc_factor = prof.procurement_academic_spike
            elif month == 8:
                proc_factor = prof.procurement_academic_spike * 0.90
            elif month in (5, 6):
                proc_factor = 0.70  # Low vacation procurement
            elif month == 12:
                proc_factor = 0.75  # Mid-year break

            proc_growth = 1.0 + 0.04 * year_offset  # ~4% annual inflation/budget growth
            proc_noise = rng.normal(1.0, 0.05)
            procurement_inr = (
                prof.base_procurement_inr
                * proc_factor
                * proc_growth
                * proc_noise
            )
            procurement_inr = max(5000.0, round(float(procurement_inr), 2))

            row = {
                "date": date_str,
                "building": prof.name,
                "electricity_kwh": electricity_kwh,
                "travel_km": travel_km,
                "waste_kg": waste_kg,
                "procurement_inr": procurement_inr,
                "student_count": student_count,
                "staff_count": staff_count,
            }
            if include_simulated_flag:
                row["is_simulated"] = True

            rows.append(row)

    df = pd.DataFrame(rows)

    # Sort logically by date and building name
    df = df.sort_values(by=["date", "building"]).reset_index(drop=True)

    if validate:
        validate_campus_activity_data(df)

    return df


def save_campus_activity_data(
    df: pd.DataFrame,
    output_path: str | Path = "data/raw/campus_activity.csv",
) -> Path:
    """
    Save the campus activity DataFrame to a CSV file.

    Parameters
    ----------
    df : pd.DataFrame
        The generated activity DataFrame.
    output_path : str | Path, default 'data/raw/campus_activity.csv'
        Destination file path.

    Returns
    -------
    Path
        Resolved Path to the saved CSV file.
    """
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(path, index=False)
    return path


def main() -> None:
    """CLI entrypoint to generate, validate, save, and inspect campus activity data."""
    parser = argparse.ArgumentParser(
        description="Generate synthetic campus activity data for BDS-36 Carbon Analytics."
    )
    parser.add_argument(
        "--start-date",
        type=str,
        default="2023-01-01",
        help="Start date YYYY-MM-01 (default: 2023-01-01)",
    )
    parser.add_argument(
        "--end-date",
        type=str,
        default="2025-12-01",
        help="End date YYYY-MM-01 (default: 2025-12-01, ~3 years = 36 months)",
    )
    parser.add_argument(
        "--num-buildings",
        type=int,
        default=5,
        help="Number of campus buildings to simulate (default: 5)",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Reproducible random seed (default: 42)",
    )
    parser.add_argument(
        "--output",
        type=str,
        default="data/raw/campus_activity.csv",
        help="Target output CSV path (default: data/raw/campus_activity.csv)",
    )

    args = parser.parse_args()

    print("=================================================================")
    print("CAMPUS CARBON ANALYTICS: SYNTHETIC ACTIVITY DATA GENERATOR")
    print("=================================================================")
    print("DISCLAIMER: All data generated is synthetic and simulated.")
    print("No external emission factors are invented or embedded in this step.")
    print(f"Date range: {args.start_date} to {args.end_date}")
    print(f"Number of buildings: {args.num_buildings}")
    print(f"Random seed: {args.seed}")
    print(f"Target destination: {args.output}")
    print("-----------------------------------------------------------------")

    df = generate_campus_activity_data(
        start_date=args.start_date,
        end_date=args.end_date,
        num_buildings=args.num_buildings,
        seed=args.seed,
        validate=True,
    )

    saved_path = save_campus_activity_data(df, args.output)
    print(f"Successfully generated and validated {len(df)} records.")
    print(f"Dataset successfully saved to: {saved_path.resolve()}\n")

    print("=== DATASET INSPECTION ===")
    print(f"Shape: {df.shape[0]} rows x {df.shape[1]} columns")
    print(f"Columns: {list(df.columns)}\n")

    print("--- Head (First 5 Rows) ---")
    print(df.head().to_string(index=False))

    print("\n--- Summary Statistics ---")
    numeric_summary = df.describe().round(2)
    print(numeric_summary.to_string())

    print("\n--- Aggregation by Building (Annualized Mean) ---")
    building_summary = (
        df.groupby("building")[
            ["electricity_kwh", "travel_km", "waste_kg", "procurement_inr", "student_count", "staff_count"]
        ]
        .mean()
        .round(2)
    )
    print(building_summary.to_string())

    print("\n--- Monthly Seasonality (Mean Across All Buildings) ---")
    df_copy = df.copy()
    df_copy["month"] = pd.to_datetime(df_copy["date"]).dt.month
    monthly_summary = (
        df_copy.groupby("month")[
            ["electricity_kwh", "travel_km", "waste_kg", "procurement_inr", "student_count"]
        ]
        .mean()
        .round(2)
    )
    print(monthly_summary.to_string())
    print("=================================================================")


if __name__ == "__main__":
    main()
